# -*- coding: utf-8 -*-
#
# Copyright (C) 2022 Graz University of Technology.
#
# invenio-workflows-tugraz is free software; you can redistribute it and/or
# modify it under the terms of the MIT License; see LICENSE file for more
# details.

on:
  push:
    tags:
      - v*

jobs:
  build-n-publish:
    uses: tu-graz-library/.github/.github/workflows/pypi-publish.yml@main
    secrets: inherit
